<?php

namespace App\Services;

use App\Models\Payment;
use App\Models\PaymentRequest;
use App\Models\Realisasi;

/**
 * Generates the automatic actual (realisasi) rows from module transactions.
 *
 * Actual is no longer entered manually; it is derived from payments:
 * - Actual Out: payment requests marked as paid, and AP settlements
 *   (payables that did not originate from a payment request).
 * - Actual In: receivable settlements (computed in MonitoringPeriodService).
 */
class ActualService
{
    /**
     * Record the actual (out) generated when a payment request is paid.
     */
    public function recordFromPaymentRequest(PaymentRequest $paymentRequest): ?Realisasi
    {
        return Realisasi::firstOrCreate(
            ['sumber' => Realisasi::SUMBER_PAYMENT_REQUEST, 'sumber_id' => $paymentRequest->id],
            [
                'project_id' => $paymentRequest->project_id,
                'akun_id' => $paymentRequest->akun_id,
                'vendor_id' => $paymentRequest->vendor_id,
                'supplier_id' => $paymentRequest->supplier_id,
                'mandor_id' => $paymentRequest->mandor_id,
                'investor_id' => $paymentRequest->investor_id,
                'tanggal' => $paymentRequest->paid_at?->toDateString() ?? now()->toDateString(),
                'nominal' => $paymentRequest->nominal,
                'keterangan' => 'Payment Request '.$paymentRequest->nomor,
            ],
        );
    }

    /**
     * Record the actual (out) generated by an AP settlement.
     *
     * Payables that came from a payment request are skipped because the
     * payment request already records its own actual when marked as paid.
     */
    public function recordFromPayablePayment(Payment $payment): ?Realisasi
    {
        $payable = $payment->payable;

        if ($payable === null || $payable->payment_request_id !== null) {
            return null;
        }

        return Realisasi::firstOrCreate(
            ['sumber' => Realisasi::SUMBER_AP_PAYMENT, 'sumber_id' => $payment->id],
            [
                'project_id' => $payable->project_id,
                'akun_id' => $payable->akun_id,
                'vendor_id' => $payable->vendor_id,
                'supplier_id' => $payable->supplier_id,
                'mandor_id' => $payable->mandor_id,
                'investor_id' => $payable->investor_id,
                'tanggal' => $payment->tanggal->toDateString(),
                'nominal' => $payment->nominal,
                'keterangan' => 'AP settlement #'.$payment->id,
            ],
        );
    }

    /**
     * Remove the actual row linked to a payment (used when a payment is deleted).
     */
    public function removeForPayment(Payment $payment): void
    {
        Realisasi::query()
            ->where('sumber', Realisasi::SUMBER_AP_PAYMENT)
            ->where('sumber_id', $payment->id)
            ->delete();
    }
}
