<?php

namespace App\Services;

use App\Models\Payment;
use App\Models\Realisasi;

/**
 * Generates the automatic actual (realisasi) rows from module transactions.
 *
 * Actual is no longer entered manually; it is derived from payments:
 * - Actual Out: AP settlements (payables settled via payments).
 * - Actual In: receivable settlements (computed in MonitoringPeriodService).
 */
class ActualService
{
    /**
     * Record the actual (out) generated by an AP settlement.
     */
    public function recordFromPayablePayment(Payment $payment): ?Realisasi
    {
        $payable = $payment->payable;

        if ($payable === null) {
            return null;
        }

        return Realisasi::firstOrCreate(
            ['sumber' => Realisasi::SUMBER_AP_PAYMENT, 'sumber_id' => $payment->id],
            [
                'project_id' => $payable->project_id,
                'akun_id' => $payable->akun_id,
                'vendor_id' => $payable->vendor_id,
                'supplier_id' => $payable->supplier_id,
                'mandor_id' => $payable->mandor_id,
                'investor_id' => $payable->investor_id,
                'tanggal' => $payment->tanggal->toDateString(),
                'nominal' => $payment->nominal,
                'keterangan' => 'AP settlement #'.$payment->id,
            ],
        );
    }

    /**
     * Remove the actual row linked to a payment (used when a payment is deleted).
     */
    public function removeForPayment(Payment $payment): void
    {
        Realisasi::query()
            ->where('sumber', Realisasi::SUMBER_AP_PAYMENT)
            ->where('sumber_id', $payment->id)
            ->delete();
    }
}
