<?php

namespace App\Services;

use App\Models\Payment;
use App\Models\Realisasi;

/**
 * Generates the automatic actual (realisasi) rows from module transactions.
 *
 * Actual is no longer entered manually; it is derived from payments:
 * - Actual Out: AP settlements (payables settled via payments).
 * - Actual In: receivable settlements (computed in MonitoringPeriodService).
 *
 * Consolidation rule: one underlying transaction must produce exactly one
 * actual (realisasi) row. When the settled payable was itself generated from
 * a manual realisasi (payable.realisasi_id set), that realisasi already IS
 * the actual row — paying it must NOT create a second row (which would
 * double-count the same expense in Budget vs Actual).
 */
class ActualService
{
    /**
     * Record the actual (out) generated by an AP settlement.
     *
     * When the payable originated from a manual realisasi, that realisasi is
     * reused (no duplicate row). A new row is only created for payables that
     * were entered manually (no originating realisasi).
     */
    public function recordFromPayablePayment(Payment $payment): ?Realisasi
    {
        $payable = $payment->payable;

        if ($payable === null) {
            return null;
        }

        // The payable was generated from a manual realisasi: that row already
        // carries the actual amount. Reuse it instead of creating a duplicate.
        if ($payable->realisasi_id !== null) {
            return $payable->realisasi;
        }

        return Realisasi::firstOrCreate(
            ['sumber' => Realisasi::SUMBER_AP_PAYMENT, 'sumber_id' => $payment->id],
            [
                'project_id' => $payable->project_id,
                'akun_id' => $payable->akun_id,
                'vendor_id' => $payable->vendor_id,
                'supplier_id' => $payable->supplier_id,
                'mandor_id' => $payable->mandor_id,
                'investor_id' => $payable->investor_id,
                'tanggal' => $payment->tanggal->toDateString(),
                'nominal' => $payment->nominal,
                'keterangan' => 'AP settlement #'.$payment->id,
            ],
        );
    }

    /**
     * Remove the actual row linked to a payment (used when a payment is deleted).
     */
    public function removeForPayment(Payment $payment): void
    {
        Realisasi::query()
            ->where('sumber', Realisasi::SUMBER_AP_PAYMENT)
            ->where('sumber_id', $payment->id)
            ->delete();
    }
}
